### ISSUE TITLE
mongo image not properly configured in development env

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction-platform#128]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

It appears that the Mongo container for the dev env is not getting properly configured by initial `make` command.  It seems that it's being set as a replica set (presumably from the `--replSet rs0` flag in the docker-compose file), but it's not receiving a proper config for that. That leaves it in a state where it's a replica set member, but neither a master or secondary.  And that blocks read/write operations (which is how I discovered this when trying to run initial migrations).

## Steps to Reproduce

Fresh clone of this repo
```sh
git clone git@github.com:reactioncommerce/reaction-development-platform.git
cd reaction-development-platform
make
```

After confirmed mongo container startup, hop into mongo client to confirm status...

```log
> rs.status()
{
    "operationTime" : Timestamp(0, 0),
    "ok" : 0,
    "errmsg" : "no replset config has been received",
    "code" : 94,
    "codeName" : "NotYetInitialized",
    "$clusterTime" : {
        "clusterTime" : Timestamp(0, 0),
        "signature" : {
            "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
            "keyId" : NumberLong(0)
        }
    }
}

> db.isMaster()
{
    "ismaster" : false,
    "secondary" : false,
    "info" : "Does not have a valid replica set config",
    "isreplicaset" : true,
    "maxBsonObjectSize" : 16777216,
    "maxMessageSizeBytes" : 48000000,
    "maxWriteBatchSize" : 100000,
    "localTime" : ISODate("2020-05-05T13:11:15.925Z"),
    "logicalSessionTimeoutMinutes" : 30,
    "connectionId" : 3,
    "minWireVersion" : 0,
    "maxWireVersion" : 8,
    "readOnly" : false,
    "ok" : 1,
    "$clusterTime" : {
        "clusterTime" : Timestamp(0, 0),
        "signature" : {
            "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
            "keyId" : NumberLong(0)
        }
    },
    "operationTime" : Timestamp(0, 0)
}
```

Specifically, note the first 4 lines from `db.isMaster()`... 

<img width="486" alt="➋_reactioncommerce_reaction_-_Gitter" src="https://user-images.githubusercontent.com/3077956/81071635-fdb45c00-8eb2-11ea-9295-3339615af92a.png">

### Versions

macOS 10.15.4
Node 12.16.3
Docker 19.03.8
Mongo 4.2.0 (dictated by this repo)

**Comment by jshimko** [comment]
Also, hello everyone.  Long time, no speak.  :)

**Comment by aldeed** [comment]
Hi @jshimko ! Did you wait for the API service to fully start? There is startup code in that service that sets up the replica set if running in dev mode. You should see logging in API service logs about it.

**Comment by jshimko** [comment]
Ok, the API container is tanking on startup (which probably explains the Mongo issue).  

Startup logs...

```log
$ docker-compose logs api

Attaching to reaction_api_1

> reaction-api@3.7.0 start /usr/local/src/app
> node --experimental-modules --experimental-json-modules ./src/index.js
(node:26) ExperimentalWarning: The ESM module loader is experimental.
16:17:50.725Z ERROR Reaction: Cannot find module /usr/local/src/app/plugins.json imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
  Error: Cannot find module /usr/local/src/app/plugins.json imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
      at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
      at Loader.resolve (internal/modules/esm/loader.js:73:33)
      at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
      at Loader.import (internal/modules/esm/loader.js:131:28)
      at importModuleDynamically (internal/modules/esm/translators.js:75:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reaction-api@3.7.0 start: `node --experimental-modules --experimental-json-modules ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reaction-api@3.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-05-05T16_17_50_739Z-debug.log
> reaction-api@3.7.0 start /usr/local/src/app
> node --experimental-modules --experimental-json-modules ./src/index.js
(node:18) ExperimentalWarning: The ESM module loader is experimental.
16:19:58.436Z ERROR Reaction: Cannot find module /usr/local/src/app/plugins.json imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
  Error: Cannot find module /usr/local/src/app/plugins.json imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
      at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
      at Loader.resolve (internal/modules/esm/loader.js:73:33)
      at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
      at Loader.import (internal/modules/esm/loader.js:131:28)
      at importModuleDynamically (internal/modules/esm/translators.js:75:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reaction-api@3.7.0 start: `node --experimental-modules --experimental-json-modules ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reaction-api@3.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-05-05T16_19_58_451Z-debug.log
```

**EDIT**: Removed original comment about docker networks.  Was a conflict on my end.

**Comment by jshimko** [comment]
Ah sorry, in regards to the first point, looks like I missed this section...

https://github.com/reactioncommerce/reaction-development-platform#network-naming-strategy

Either way, I had to manually create that network for some reason.  Will try to get more specific errors on that.

**Comment by aldeed** [comment]
Yeah, let's close this as a side effect of https://github.com/reactioncommerce/reaction/issues/6243
