### ISSUE TITLE
reaction identity can't access the overlay network 

### ISSUE THREAD

**Issue by mamged** [reactioncommerce/reaction-platform#136]
## Issue Description
I'm trying to run reaction, I'm getting blank screen.
Then I found that the error is from identity service.
I'm not sure why I get this error `HTTP request to Hydra:  FetchError: request to http://hydra.reaction.localhost:4445/oauth2/auth/requests/login?login_challenge=b6921ac0f139418eb274fc831d14247f failed, reason: getaddrinfo ENOTFOUND hydra.reaction.localhost `
Although when I try to access this url from chrome I get the expect response.

### logs
```
I20200613-09:50:59.092(2)?   NODE_ENV: 'development',
I20200613-09:50:59.092(2)?   PORT: '25881',
I20200613-09:50:59.093(2)?   ROOT_URL: 'http://localhost:4100/',
I20200613-09:50:59.093(2)?   MONGO_URL: 'mongodb://mongo.reaction.localhost:27017/reaction',
I20200613-09:50:59.094(2)?   MOBILE_DDP_URL: 'http://localhost:4100/',
I20200613-09:50:59.095(2)?   MOBILE_ROOT_URL: 'http://localhost:4100/',
I20200613-09:50:59.096(2)?   MONGO_OPLOG_URL: 'mongodb://mongo.reaction.localhost:27017/local',
I20200613-09:50:59.097(2)?   APP_ID: 'nu5d9iq7wnpr.lvmyo794449',
I20200613-09:50:59.110(2)?   METEOR_AUTO_RESTART: 'true',
I20200613-09:50:59.111(2)?   HTTP_FORWARDED_COUNT: '1',
I20200613-09:50:59.112(2)?   METEOR_SHELL_DIR: '/Users/m/My-Lab/ecommerce/reaction-development-platform/reaction-identity/.meteor/local/shell',
I20200613-09:50:59.114(2)?   METEOR_PARENT_PID: '32026',
I20200613-09:50:59.115(2)?   METEOR_PRINT_ON_LISTEN: 'true',
I20200613-09:50:59.115(2)?   TEST_METADATA: '{}',
I20200613-09:50:59.116(2)?   API_URL: 'http://localhost:3000/graphql',
I20200613-09:50:59.116(2)?   HYDRA_ADMIN_URL: 'http://hydra.reaction.localhost:4445',
I20200613-09:50:59.116(2)?   HYDRA_TOKEN_URL: 'http://hydra.reaction.localhost:4444/oauth2/token',
I20200613-09:50:59.116(2)?   LOG_LEVEL: 'debug',
I20200613-09:50:59.117(2)?   METEOR_DISABLE_OPTIMISTIC_CACHING: '1',
I20200613-09:50:59.117(2)?   METEOR_WATCH_POLLING_INTERVAL_MS: '10000',
I20200613-09:50:59.117(2)?   OAUTH2_CLIENT_DOMAINS: 'http://localhost:4000'
I20200613-09:50:59.117(2)? }
I20200613-09:50:59.118(2)? 07:50:58.701Z  INFO Reaction: Serving Reaction Identity at http://localhost:4100/
=> Started your app.

=> App running at: http://localhost:4100/
I20200613-09:51:06.043(2)? 07:51:05.968Z ERROR Reaction:
I20200613-09:51:06.046(2)?   An error occurred while making GET http://hydra.reaction.localhost:4445/oauth2/auth/requests/login?login_challenge=b6921ac0f139418eb274fc831d14247f HTTP request to Hydra:  FetchError: request to http://hydra.reaction.localhost:4445/oauth2/auth/requests/login?login_challenge=b6921ac0f139418eb274fc831d14247f failed, reason: getaddrinfo ENOTFOUND hydra.reaction.localhost
I20200613-09:51:06.047(2)?       at ClientRequest.<anonymous> (/Users/m/My-Lab/ecommerce/reaction-development-platform/reaction-identity/node_modules/node-fetch/lib/index.js:1455:11)
I20200613-09:51:06.047(2)?       at ClientRequest.emit (events.js:311:20)
I20200613-09:51:06.047(2)?       at ClientRequest.EventEmitter.emit (domain.js:482:12)
I20200613-09:51:06.047(2)?       at Socket.socketErrorListener (_http_client.js:426:9)
I20200613-09:51:06.047(2)?       at Socket.emit (events.js:311:20)
I20200613-09:51:06.047(2)?       at Socket.EventEmitter.emit (domain.js:482:12)
I20200613-09:51:06.048(2)?       at emitErrorNT (internal/streams/destroy.js:92:8)
I20200613-09:51:06.048(2)?       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
I20200613-09:51:06.048(2)?       at processTicksAndRejections (internal/process/task_queues.js:84:21)
I20200613-09:51:06.048(2)?    => awaited here:
I20200613-09:51:06.049(2)?       at Function.Promise.await (/Users/m/.meteor/packages/promise/.0.11.2.1e1wn8z.joczg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200613-09:51:06.049(2)?       at server/hydra.js:34:14
I20200613-09:51:06.049(2)?       at /Users/m/.meteor/packages/promise/.0.11.2.1e1wn8z.joczg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
I20200613-09:51:06.050(2)?     message: 'request to http://hydra.reaction.localhost:4445/oauth2/auth/requests/login?login_challenge=b6921ac0f139418eb274fc831d14247f failed, reason: getaddrinfo ENOTFOUND hydra.reaction.localhost',
I20200613-09:51:06.050(2)?     type: 'system',
I20200613-09:51:06.051(2)?     errno: 'ENOTFOUND',
I20200613-09:51:06.051(2)?     code: 'ENOTFOUND'
I20200613-09:51:06.052(2)?   }
I20200613-09:51:06.052(2)? 07:51:06.047Z ERROR Reaction: Error while performing Hydra request
I20200613-09:51:06.053(2)?   FetchError: request to http://hydra.reaction.localhost:4445/oauth2/auth/requests/login?login_challenge=b6921ac0f139418eb274fc831d14247f failed, reason: getaddrinfo ENOTFOUND hydra.reaction.localhost
I20200613-09:51:06.056(2)?       at ClientRequest.<anonymous> (/Users/m/My-Lab/ecommerce/reaction-development-platform/reaction-identity/node_modules/node-fetch/lib/index.js:1455:11)
I20200613-09:51:06.057(2)?       at ClientRequest.emit (events.js:311:20)
I20200613-09:51:06.058(2)?       at ClientRequest.EventEmitter.emit (domain.js:482:12)
I20200613-09:51:06.059(2)?       at Socket.socketErrorListener (_http_client.js:426:9)
I20200613-09:51:06.060(2)?       at Socket.emit (events.js:311:20)
I20200613-09:51:06.061(2)?       at Socket.EventEmitter.emit (domain.js:482:12)
I20200613-09:51:06.061(2)?       at emitErrorNT (internal/streams/destroy.js:92:8)
I20200613-09:51:06.062(2)?       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
I20200613-09:51:06.062(2)?       at processTicksAndRejections (internal/process/task_queues.js:84:21)
I20200613-09:51:06.063(2)?    => awaited here:
I20200613-09:51:06.063(2)?       at Function.Promise.await (/Users/m/.meteor/packages/promise/.0.11.2.1e1wn8z.joczg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200613-09:51:06.064(2)?       at server/hydra.js:34:14
I20200613-09:51:06.064(2)?       at /Users/m/.meteor/packages/promise/.0.11.2.1e1wn8z.joczg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200613-09:51:06.065(2)? 07:51:06.047Z  WARN Reaction: No HYDRA_OAUTH2_ERROR_URL set in ENV.
```
I tried to run it from inside the docker container and without the container and I get the same error.

## Steps to Reproduce
1. make stop
2. make start
3. open `http://reaction.localhost:4000/`
4. click "Create Account"
5. redirected the page to `localhost:4100/login?login_challenge=b6921ac0f139418eb274fc831d14247f`
5. I got blank screen.

### Versions
latest

**Comment by kieckhafer** [comment]
Can you try step 3 without `reaction`, just going to `http://localhost:4000`, and see what happens?
