### ISSUE TITLE
reaction-development-platform api not working using make

### ISSUE THREAD

**Issue by webtsys** [reactioncommerce/reaction-platform#170]
## Prerequisites
* [X ] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue? Yes, in debian Buster, Ubuntu 20.04, Opensuse Leap 15.2 and Archlinux.
* [X] Did you search the issue queue for existing issue? Yes.

## Issue Description
When download "reaction-development-platform" and execute "make" following the instructions, api platform don't work because system cannot connect to docker mongodb: 

Log executing 

docker-compose logs -f

mongo_1  | 2021-02-12T15:06:09.835+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
mongo_1  | 2021-02-12T15:06:09.836+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
mongo_1  | 2021-02-12T15:06:09.836+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
mongo_1  | 2021-02-12T15:06:09.836+0000 I  CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
mongo_1  | 2021-02-12T15:06:09.836+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.system.sessions as collection version: <unsharded>
mongo_1  | 2021-02-12T15:06:09.836+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
mongo_1  | 2021-02-12T15:06:10.001+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
mongo_1  | 2021-02-12T15:06:16.162+0000 I  NETWORK  [listener] connection accepted from 172.24.0.5:41396 #1 (1 connection now open)
mongo_1  | 2021-02-12T15:06:16.171+0000 I  NETWORK  [conn1] received client metadata from 172.24.0.5:41396 conn1: { driver: { name: "nodejs", version: "3.6.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v14.15.0, LE (unified)" }
mongo_1  | 2021-02-12T15:06:26.333+0000 I  NETWORK  [listener] connection accepted from 172.24.0.6:52642 #2 (2 connections now open)
mongo_1  | 2021-02-12T15:06:26.347+0000 I  NETWORK  [conn2] received client metadata from 172.24.0.6:52642 conn2: { driver: { name: "nodejs", version: "3.5.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v12.16.1, LE (unified)" }
mongo_1  | 2021-02-12T15:06:26.364+0000 I  NETWORK  [listener] connection accepted from 172.24.0.6:52644 #3 (3 connections now open)
mongo_1  | 2021-02-12T15:06:26.365+0000 I  NETWORK  [conn3] received client metadata from 172.24.0.6:52644 conn3: { driver: { name: "nodejs", version: "3.5.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v12.16.1, LE (unified)" }
mongo_1  | 2021-02-12T15:06:42.443+0000 I  NETWORK  [listener] connection accepted from 172.24.0.7:42066 #4 (4 connections now open)
mongo_1  | 2021-02-12T15:06:42.451+0000 I  NETWORK  [conn4] received client metadata from 172.24.0.7:42066 conn4: { driver: { name: "nodejs", version: "3.5.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v12.16.1, LE (unified)" }
mongo_1  | 2021-02-12T15:06:42.463+0000 I  NETWORK  [listener] connection accepted from 172.24.0.7:42068 #5 (5 connections now open)
mongo_1  | 2021-02-12T15:06:42.464+0000 I  NETWORK  [conn5] received client metadata from 172.24.0.7:42068 conn5: { driver: { name: "nodejs", version: "3.5.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v12.16.1, LE (unified)" }
mongo_1  | 2021-02-12T15:06:46.164+0000 I  NETWORK  [conn1] end connection 172.24.0.5:41396 (4 connections now open)
mongo_1  | 2021-02-12T15:06:46.169+0000 I  NETWORK  [listener] connection accepted from 172.24.0.5:41574 #6 (5 connections now open)
mongo_1  | 2021-02-12T15:06:46.170+0000 I  NETWORK  [conn6] received client metadata from 172.24.0.5:41574 conn6: { driver: { name: "nodejs", version: "3.6.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.15-arch1-1" }, platform: "'Node.js v14.15.0, LE (unified)" }
mongo_1  | 2021-02-12T15:07:16.169+0000 I  NETWORK  [conn6] end connection 172.24.0.5:41574 (4 connections now open)
mongo_1  | 2021-02-12T15:07:35.289+0000 I  NETWORK  [listener] connection accepted from 172.24.0.1:53238 #7 (5 connections now open)
mongo_1  | 2021-02-12T15:07:35.289+0000 I  NETWORK  [conn7] Error receiving request from client: ProtocolError: Client sent an HTTP request over a native MongoDB connection. Ending connection from 172.24.0.1:53238 (connection id: 7)
mongo_1  | 2021-02-12T15:07:35.289+0000 I  NETWORK  [conn7] end connection 172.24.0.1:53238 (4 connections now open)
mongo_1  | 2021-02-12T15:07:35.306+0000 I  NETWORK  [listener] connection accepted from 172.24.0.1:53242 #8 (5 connections now open)
mongo_1  | 2021-02-12T15:07:35.306+0000 I  NETWORK  [conn8] Error receiving request from client: ProtocolError: Client sent an HTTP request over a native MongoDB connection. Ending connection from 172.24.0.1:53242 (connection id: 8)
mongo_1  | 2021-02-12T15:07:35.306+0000 I  NETWORK  [conn8] end connection 172.24.0.1:53242 (4 connections now open)
mongo_1  | 2021-02-12T15:08:25.654+0000 I  NETWORK  [conn3] end connection 172.24.0.6:52644 (3 connections now open)
mongo_1  | 2021-02-12T15:08:25.654+0000 I  NETWORK  [conn2] end connection 172.24.0.6:52642 (2 connections now open)
mongo_1  | 2021-02-12T15:08:41.758+0000 I  NETWORK  [conn5] end connection 172.24.0.7:42068 (1 connection now open)
mongo_1  | 2021-02-12T15:08:41.758+0000 I  NETWORK  [conn4] end connection 172.24.0.7:42066 (0 connections now open)
mongo_1  | 2021-02-12T15:11:09.835+0000 I  CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
mongo_1  | 2021-02-12T15:11:09.835+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
api_1    | 
api_1    | > reaction-api@3.11.0 start /usr/local/src/app
api_1    | > node --experimental-modules --experimental-json-modules ./src/index.js
api_1    | 
api_1    | (node:28) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
api_1    | (Use `node --trace-warnings ...` to show where the warning was created)
api_1    | 15:06:16.117Z  INFO Reaction: Registered plugin simple-schema (1.0.1)
api_1    | 15:06:16.119Z  INFO Reaction: Registered plugin job-queue (1.0.2)
api_1    | 15:06:16.120Z  INFO Reaction: Registered plugin files (1.0.13)
api_1    | 15:06:16.121Z  INFO Reaction: Registered plugin shops (1.2.0)
api_1    | 15:06:16.121Z  INFO Reaction: Registered plugin settings (1.0.2)
api_1    | 15:06:16.121Z  INFO Reaction: Registered plugin i18n (1.0.3)
api_1    | 15:06:16.122Z  INFO Reaction: Registered plugin email (1.0.1)
api_1    | 15:06:16.123Z  INFO Reaction: Registered plugin address-validation (1.3.1)
api_1    | 15:06:16.123Z  INFO Reaction: Registered plugin plugin-translations (1.1.2)
api_1    | 15:06:16.123Z  INFO Reaction: Registered plugin system-information (1.1.1)
api_1    | 15:06:16.123Z  INFO Reaction: Registered plugin email-smtp (1.0.3)
api_1    | 15:06:16.124Z  INFO Reaction: Registered plugin email-templates (1.0.1)
api_1    | 15:06:16.125Z  INFO Reaction: Registered plugin accounts (1.6.0)
api_1    | 15:06:16.126Z  INFO Reaction: Registered plugin authentication (1.2.0)
api_1    | 15:06:16.126Z  INFO Reaction: Registered plugin authorization-simple (1.3.1)
api_1    | 15:06:16.127Z  INFO Reaction: Registered plugin products (1.0.2)
api_1    | 15:06:16.129Z  INFO Reaction: Registered plugin catalogs (1.0.5)
api_1    | 15:06:16.130Z  INFO Reaction: Registered plugin tags (1.0.4)
api_1    | 15:06:16.131Z  INFO Reaction: Registered plugin pricing-simple (1.0.1)
api_1    | 15:06:16.132Z  INFO Reaction: Registered plugin inventory (1.0.3)
api_1    | 15:06:16.132Z  INFO Reaction: Registered plugin inventory-simple (1.0.3)
api_1    | 15:06:16.133Z  INFO Reaction: Registered plugin carts (1.2.2)
api_1    | 15:06:16.134Z  INFO Reaction: Registered plugin orders (1.2.3)
api_1    | 15:06:16.135Z  INFO Reaction: Registered plugin payments (1.0.1)
api_1    | 15:06:16.135Z  INFO Reaction: Registered plugin payments-stripe (1.0.2)
api_1    | 15:06:16.135Z  INFO Reaction: Registered plugin payments-example (1.1.1)
api_1    | 15:06:16.136Z  INFO Reaction: Registered plugin discounts (1.0.1)
api_1    | 15:06:16.136Z  INFO Reaction: Registered plugin discounts-codes (3.11.0)
api_1    | 15:06:16.137Z  INFO Reaction: Registered plugin surcharges (1.1.2)
api_1    | 15:06:16.137Z  INFO Reaction: Registered plugin shipments (1.0.1)
api_1    | 15:06:16.138Z  INFO Reaction: Registered plugin shipments-flat-rate (1.0.4)
api_1    | 15:06:16.138Z  INFO Reaction: Registered plugin taxes (1.1.1)
api_1    | 15:06:16.139Z  INFO Reaction: Registered plugin taxes-flat-rate (1.0.4)
api_1    | 15:06:16.139Z  INFO Reaction: Registered plugin navigation (1.1.1)
api_1    | 15:06:16.140Z  INFO Reaction: Registered plugin sitemap-generator (1.2.1)
api_1    | 15:06:16.140Z  INFO Reaction: Registered plugin notifications (1.0.1)
api_1    | 15:06:16.140Z  INFO Reaction: Registered plugin address-validation-test (1.0.1)
api_1    | 15:06:16.143Z  INFO Reaction: Initializing MongoDB replica set...
api_1    | 15:06:16.145Z  INFO Reaction: Connecting to MongoDB...
api_1    | 15:06:46.166Z  WARN Reaction: Failed to initialize a MongoDB replica set. This may result in errors or some things not working. Error: Server selection timed out after 30000 ms
api_1    | 15:06:46.166Z  INFO Reaction: Connecting to MongoDB...
api_1    | 15:07:16.170Z ERROR Reaction: Server selection timed out after 30000 ms
api_1    |   MongoServerSelectionError: Server selection timed out after 30000 ms
api_1    |       at Timeout._onTimeout (/usr/local/src/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
api_1    |       at listOnTimeout (internal/timers.js:554:17)
api_1    |       at processTimers (internal/timers.js:497:7)
api_1    | npm ERR! code ELIFECYCLE
api_1    | npm ERR! errno 1
api_1    | npm ERR! reaction-api@3.11.0 start: `node --experimental-modules --experimental-json-modules ./src/index.js`
api_1    | npm ERR! Exit status 1
api_1    | npm ERR! 
api_1    | npm ERR! Failed at the reaction-api@3.11.0 start script.
api_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1    | 
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /home/node/.npm/_logs/2021-02-12T15_07_16_205Z-debug.log
api_1    | reaction_api_1 exited with code 1

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Execute make
2. Wait.

Using:

nodejs 15.8.0
npm 6.14.11

### Versions

Last version

**Comment by webtsys** [comment]
Working now with last updates in repository.
