### ISSUE TITLE
Problem with storefront installation

### ISSUE THREAD

**Issue by okazdal** [reactioncommerce/reaction-platform#73]
All containers are running except storefront.

Any suggestions?

Here is logs for storefront container:

Fixing volume /home/node/.cache/yarn (before=0:0 after=1000:1000)…✓
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cookie-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/src/reaction-app/src/server.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by RoytenBerge** [comment]
Hey Okazdal,

I had the same issue.
This solved the issue for me:
https://github.com/reactioncommerce/reaction/issues/5573#issue-496294395

**Comment by okazdal** [comment]
Yep. That fixed it. Thank you for your help.
